from enum import StrEnum


class NotificationType(StrEnum):
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED"
    TASK_DEADLINE_CHANGED = "TASK_DEADLINE_CHANGED"
    TASK_COMPLETED = "TASK_COMPLETED"
    PROJECT_INVITATION = "PROJECT_INVITATION"
    PROJECT_MEMBER_ADDED = "PROJECT_MEMBER_ADDED"
