from typing import Protocol
from uuid import UUID
from app.domain.entities.project import Project
from app.domain.entities.project_member import ProjectMember


class ProjectRepository(Protocol):
    async def create(self, project: Project) -> Project: ...

    async def get(self, project_id: UUID) -> Project | None: ...

    async def update(self, project: Project) -> Project: ...

    async def list_for_user(self, user_id: UUID, offset: int, limit: int) -> tuple[list[Project], int]: ...

    async def get_member(self, project_id: UUID, user_id: UUID) -> ProjectMember | None: ...

    async def list_members(self, project_id: UUID) -> list[ProjectMember]: ...

    async def add_member(self, member: ProjectMember) -> ProjectMember: ...

    async def remove_member(self, project_id: UUID, user_id: UUID) -> None: ...
