from typing import Protocol
from uuid import UUID
from app.domain.entities.team import Team
from app.domain.entities.team_member import TeamMember


class TeamRepository(Protocol):
    async def create(self, team: Team) -> Team: ...

    async def get(self, team_id: UUID) -> Team | None: ...

    async def update(self, team: Team) -> Team: ...

    async def delete(self, team_id: UUID) -> None: ...

    async def list_for_user(self, user_id: UUID, offset: int, limit: int) -> tuple[list[Team], int]: ...

    async def get_member(self, team_id: UUID, user_id: UUID) -> TeamMember | None: ...

    async def add_member(self, member: TeamMember) -> TeamMember: ...
