from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.entities.notification import Notification
from app.domain.enums.notification_type import NotificationType


class NotificationRepository(Protocol):
    async def add(self, notification: Notification) -> None: ...
    async def get_for_user(self, user_id: UUID, *, page: int, page_size: int, type: NotificationType | None, is_read: bool | None, from_date: datetime | None, to_date: datetime | None) -> tuple[list[Notification], int]: ...
    async def get(self, notification_id: UUID) -> Notification | None: ...
    async def mark_read(self, notification_id: UUID, user_id: UUID) -> bool: ...
    async def mark_all_read(self, user_id: UUID) -> None: ...
