from abc import ABC, abstractmethod
from uuid import UUID
from app.domain.entities.task import Task


class TaskRepository(ABC):
    @abstractmethod
    async def add(self, task: Task) -> None: ...
    @abstractmethod
    async def get(self, task_id: UUID) -> Task | None: ...
    @abstractmethod
    async def update(self, task: Task) -> None: ...
    @abstractmethod
    async def delete(self, task_id: UUID) -> None: ...
    @abstractmethod
    async def list(self, **filters): ...
    @abstractmethod
    async def get_overdue(self, **filters): ...
    @abstractmethod
    async def count_project_statistics(self, project_id: UUID) -> dict: ...
